import { Serie } from "./series.js";
export var series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://i.imgur.com/GGje0vc.jpg"),
    new Serie(2, "Malcolm in the Middle", "FOX", 7, "Malcolm in the Middle (en España y parte de Hispanoamérica Malcolm y en México Malcolm el de en medio) es una serie de televisión cómica creada por Linwood Boomer de la cadena FOX. La serie comenzó a transmitirse el 9 de enero de 2000 y finalizó el 14 de mayo de 2006, luego de siete temporadas y 151 episodios. La serie recibió elogios de la crítica, y ganó un Peabody, siete premios Emmy, un Grammy y fue siete veces nominada al Globo de Oro.", "https://www.disneyplus.com/es-419/series/malcolm-in-the-middle/5mNQERYSP5YN", "https://flxt.tmsimg.com/assets/p7896129_b_v13_aa.jpg"),
    new Serie(3, "The Amazing World of Gumball", "Cartoon Network", 6, "The series revolves around the life of a 12-year-old cat named Gumball Watterson and his frequent shenanigans in the fictional American city of Elmore, accompanied by his adopted goldfish brother and best friend Darwin. Gumball's other family members—his intellectual sister Anais and stay-at-home father Richard, both rabbits, and workaholic mother Nicole, a cat—often find themselves involved in Gumball's exploits. Gumball attends school with his siblings at Elmore Junior High, where throughout the series he interacts with his various middle school classmates, most prominently his love interest Penny Fitzgerald.", "https://www.hbomax.com/co/es/series/urn:hbo:series:GXkyElw3j2J4_wwEAAAQa", "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/ee852eb7c6b310b0abc08ffdb4a493114fc4ef6067b59906deeebf96107b8854._RI_V_TTW_.jpg"),
    new Serie(4, "How I Met your Mother", "FOX", 9, "En el año 2030, el arquitecto Ted Mosby (Josh Radnor) decide contarles a sus dos hijos la historia de cómo conoció a su madre. Por lo tanto, inicia una narración de recuerdos recopilados desde el 2005, año en el que dos de sus mejores amigos, Marshall Eriksen (Jason Segel) y Lily Aldrin (Alyson Hannigan), deciden casarse tras nueve años de noviazgo. Esa decisión hace que Ted, soltero empedernido, al igual que su otro mejor amigo Barney Stinson (Neil Patrick Harris), decida encontrar al amor de su vida desesperadamente. De una manera curiosa, aparece en ese instante la reportera canadiense Robin Scherbatsky (Cobie Smulders), que se convertirá en una nueva amiga del grupo y parte importante en la vida de Ted. A partir de este hecho, inicia la búsqueda implacable de una esposa que se convierta en madre de sus hijos. ", "https://www.starplus.com/es-419/series/how-i-met-your-mother/3kpBeRQiKjkq", "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/2970945770FC137FF7D5D3408D5D40836FD4C715DE6A1744F6F5AF21B2386827/scale?width=1200&aspectRatio=1.78&format=jpeg"),
    new Serie(5, "Modern Family", "FOX", 11, " La serie sigue la vida de Jay Pritchett y su familia, todos los cuales viven en Los Ángeles. La familia de Jay Pritchett incluye a su segunda esposa y su hijastro, así como a sus dos hijos adultos; sus esposos e hijos y nietos. Modern Family consta de once temporadas en total. ", "https://www.starplus.com/es-419/series/modern-family/6p2yzz9mh8Kp", "https://images.justwatch.com/poster/243955028/s718/modern-family.%7Bformat%7D"),
    new Serie(6, "Better Call Saul", "SONY", 6, "Better Call Saul sigue la transformación de Jimmy McGill (Bob Odenkirk), un ex estafador que intenta convertirse en un abogado respetable, a la personalidad del extravagante abogado penalista Saul Goodman (un juego de palabras con la frase \"[it]'s all good, man!\"), seis años antes de aliarse con Walter White en Breaking Bad. ", "https://www.netflix.com/title/80021955", "https://e.rpp-noticias.io/normal/2022/02/10/251325_1215477.jpg"),
];
